name: rive
description: Rive 2 Flutter Runtime. This package provides runtime functionality for playing back and interacting with animations built with the Rive editor available at https://rive.app.
version: 0.6.6+1
repository: https://github.com/rive-app/rive-flutter
homepage: https://rive.app

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphs: ^0.2.0
  meta: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
