name: rive
description: Rive Flutter Runtime
version: 0.0.1
author:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphs: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: